apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
data: 
  aws_access_key_id: QUtJQVhBNUVYWFlUMjZOMkgzVVE=
  aws_secret_access_key: RlBsR1lRVFpPU1V4TWlUMklGcm44MjZwd2t6TzhkYXY0TWxiVjFLbw==