apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed-deployment
  labels:
    app: backend-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: dreamchild/udagram-api-feed:latest
        ports:
        - containerPort: 80